spring:
  datasource:
    username: root
    password: Ayush@3344
    url: jdbc:mysql://localhost:3306/moviedb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: src/main/resources/static/posters/



base:
  url: "http://localhost:8080"

server:
  port: 8081